/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainWindows.java
 *
 * Created on 16 juin 2011, 10:59:54
 */
package GUI;

import Utils.ApplicationLauncher;
import Model.ModelManager;
import Utils.ExtensionFileFilter;
import Utils.FileLocator;
import java.io.File;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author fifi
 */
public class mainWindows extends javax.swing.JFrame {

    /** Creates new form mainWindows */
    public mainWindows() {
        
        //A start of application, ask to Model to try to find a XML config in user's folder
        ModelManager.init();
        
        /**
         * init graphicals components
         */
        initComponents();
        
        /**
         * init graphicals informations from the Model
         */
        initializeText();
    }
    
    /**
     *  This method is called in order to initialize all labelText
     */
    private void initializeText() {
        
        //Initialized Title
        setTitle(TITLE_MAIN_FRAME);
        
        //Initialize Location Text
        configLocationVar.setText( ModelManager.getXMLFileName() );
        configLocationVar.setEditable(false);
        
        //Init conf file
        LOGS_FILE_PATH = fileLocator.getPathOfFile(LOGS_FILE_PATH);
        
        //Init XSD file
        ModelManager.setXSDFileName( fileLocator.getPathOfFile( ModelManager.getXSDFileName() ));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTitle = new javax.swing.JPanel();
        titleText1 = new javax.swing.JLabel();
        titleText2 = new javax.swing.JLabel();
        titleText3 = new javax.swing.JLabel();
        titleURL1 = new javax.swing.JLabel();
        titleURL2 = new javax.swing.JLabel();
        titlePicture = new javax.swing.JLabel();
        PanelConfig = new javax.swing.JPanel();
        configLocationText = new javax.swing.JLabel();
        configLocationVar = new javax.swing.JTextField();
        configBrowse = new javax.swing.JButton();
        configTextEdit = new javax.swing.JButton();
        configGUIEdit = new javax.swing.JButton();
        PanelInfo = new javax.swing.JPanel();
        infoStatus = new javax.swing.JLabel();
        infoStatusVar = new javax.swing.JLabel();
        infoNbRun = new javax.swing.JLabel();
        infoNbRunVar = new javax.swing.JLabel();
        PanelLogs = new javax.swing.JPanel();
        logsView = new javax.swing.JLabel();
        logsNotepad = new javax.swing.JButton();
        logsExplorer = new javax.swing.JButton();
        PanelControl = new javax.swing.JPanel();
        controlStart = new javax.swing.JButton();
        controlStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setLocationByPlatform(true);
        setResizable(false);

        PanelTitle.setBackground(new java.awt.Color(255, 255, 255));

        titleText1.setText("ProActiveAgent v2.3.2     ");

        titleText2.setText("(C) 1997-2011 INRIA/University of");

        titleText3.setText("Nice-Sophia Antipolis/ActiveEon");

        titleURL1.setText("http://proactive.inria.fr");

        titleURL2.setText("http://www.activeeon.com");

        titlePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/ActiveEon.png"))); // NOI18N
        titlePicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToProactiveWebSite(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelTitleLayout = new org.jdesktop.layout.GroupLayout(PanelTitle);
        PanelTitle.setLayout(PanelTitleLayout);
        PanelTitleLayout.setHorizontalGroup(
            PanelTitleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelTitleLayout.createSequentialGroup()
                .add(titlePicture, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 382, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(28, 28, 28)
                .add(PanelTitleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(titleText3)
                    .add(titleURL2)
                    .add(titleURL1)
                    .add(titleText2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .add(titleText1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelTitleLayout.setVerticalGroup(
            PanelTitleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelTitleLayout.createSequentialGroup()
                .add(PanelTitleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(PanelTitleLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(titleText1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(titleText2)
                        .add(1, 1, 1)
                        .add(titleText3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(titleURL1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(titleURL2))
                    .add(titlePicture, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        PanelConfig.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuration"));

        configLocationText.setText("Location:");

        configBrowse.setText("Browse");
        configBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseOnClick(evt);
            }
        });

        configTextEdit.setText("Text Edit");
        configTextEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchLocationOnEditor(evt);
            }
        });

        configGUIEdit.setText("GUI Edit");
        configGUIEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIEditOnClick(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelConfigLayout = new org.jdesktop.layout.GroupLayout(PanelConfig);
        PanelConfig.setLayout(PanelConfigLayout);
        PanelConfigLayout.setHorizontalGroup(
            PanelConfigLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelConfigLayout.createSequentialGroup()
                .add(PanelConfigLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelConfigLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(configLocationText)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(configLocationVar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                        .add(6, 6, 6)
                        .add(configBrowse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelConfigLayout.createSequentialGroup()
                        .add(386, 386, 386)
                        .add(configGUIEdit)
                        .add(6, 6, 6)
                        .add(configTextEdit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );

        PanelConfigLayout.linkSize(new java.awt.Component[] {configBrowse, configGUIEdit, configTextEdit}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        PanelConfigLayout.setVerticalGroup(
            PanelConfigLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelConfigLayout.createSequentialGroup()
                .add(PanelConfigLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(configLocationText)
                    .add(configLocationVar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(configBrowse))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PanelConfigLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(configTextEdit)
                    .add(configGUIEdit))
                .addContainerGap())
        );

        PanelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));

        infoStatus.setText("Status:");

        infoStatusVar.setText("Stopped");

        infoNbRun.setText("Spawned Running:");

        infoNbRunVar.setText("0");

        org.jdesktop.layout.GroupLayout PanelInfoLayout = new org.jdesktop.layout.GroupLayout(PanelInfo);
        PanelInfo.setLayout(PanelInfoLayout);
        PanelInfoLayout.setHorizontalGroup(
            PanelInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelInfoLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(PanelInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, infoStatus)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, infoNbRun))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 14, Short.MAX_VALUE)
                .add(PanelInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(infoStatusVar)
                    .add(infoNbRunVar))
                .add(20, 20, 20))
        );
        PanelInfoLayout.setVerticalGroup(
            PanelInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelInfoLayout.createSequentialGroup()
                .add(7, 7, 7)
                .add(PanelInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(infoStatus)
                    .add(infoStatusVar))
                .add(18, 18, 18)
                .add(PanelInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(infoNbRunVar)
                    .add(infoNbRun))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        PanelLogs.setBorder(javax.swing.BorderFactory.createTitledBorder("Logs"));

        logsView.setText("View Logs");
        logsView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openLogFolder(evt);
            }
        });

        logsNotepad.setText("with Editor");
        logsNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchLogsOnEditor(evt);
            }
        });

        logsExplorer.setText("with Browser");
        logsExplorer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchLogsOnBrowser(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelLogsLayout = new org.jdesktop.layout.GroupLayout(PanelLogs);
        PanelLogs.setLayout(PanelLogsLayout);
        PanelLogsLayout.setHorizontalGroup(
            PanelLogsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelLogsLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(logsView)
                .add(18, 18, 18)
                .add(PanelLogsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(logsExplorer)
                    .add(logsNotepad))
                .addContainerGap())
        );

        PanelLogsLayout.linkSize(new java.awt.Component[] {logsExplorer, logsNotepad}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        PanelLogsLayout.setVerticalGroup(
            PanelLogsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelLogsLayout.createSequentialGroup()
                .add(PanelLogsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelLogsLayout.createSequentialGroup()
                        .add(logsNotepad)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(logsExplorer))
                    .add(PanelLogsLayout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(logsView)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelControl.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));

        controlStart.setText("Start");
        controlStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlStartActionPerformed(evt);
            }
        });

        controlStop.setText("Stop");
        controlStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlStopActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelControlLayout = new org.jdesktop.layout.GroupLayout(PanelControl);
        PanelControl.setLayout(PanelControlLayout);
        PanelControlLayout.setHorizontalGroup(
            PanelControlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelControlLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .add(PanelControlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, controlStop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, controlStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PanelControlLayout.setVerticalGroup(
            PanelControlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelControlLayout.createSequentialGroup()
                .add(controlStart)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(controlStop)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelConfig, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(PanelInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PanelLogs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PanelControl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {PanelInfo, PanelLogs}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(PanelTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PanelConfig, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(PanelInfo, 0, 93, Short.MAX_VALUE)
                    .add(PanelControl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(PanelLogs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * browse XML Config File
     * @param evt 
     */
    private void browseOnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseOnClick
        
        FileFilter filter = new ExtensionFileFilter("XML Files", new String[] { "XML", "xml" });
        
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(filter);
        fc.setCurrentDirectory(new java.io.File("."));
        fc.setDialogTitle("Choose your configuration file");
        fc.showOpenDialog(this);
        File selFile = fc.getSelectedFile();
       
        if(selFile != null) {
            configLocationVar.setText(selFile.getAbsolutePath());
            ModelManager.setXMLFileName(configLocationVar.getText());
        }
    }//GEN-LAST:event_browseOnClick

    /**
     * The START method
     * @param evt 
     */
    private void controlStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlStartActionPerformed
        sysTray.setIcon( SystemTray.STATUS.RUNNING  );
        infoStatusVar.setText("Running");
        appLauncher.launchScreenSaver();
    }//GEN-LAST:event_controlStartActionPerformed

    /**
     * 
     * @param evt 
     */
    private void GUIEditOnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIEditOnClick
        
        //Init Config
        if(ModelManager.loadXML(this)) {
            System.out.println("open : " + ModelManager.getXMLFileName() + " [OK] ");
        } else {
            System.out.println("open : " + ModelManager.getXMLFileName() + " [FAIl] ");
        }
        GUIEditWindows.initializeText();
        GUIEditWindows.setVisible(true);
    }//GEN-LAST:event_GUIEditOnClick

    /**
     * Launch editor with Logs file in order ton edit it
     * @param evt 
     */
    private void launchLogsOnEditor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchLogsOnEditor
        
        File log = new File( LOGS_FILE_PATH );
        if(log.exists()) {
            appLauncher.executeEditor(LOGS_FILE_PATH);
        } else {
            System.out.println("Logs file was not found.");
        }
    }//GEN-LAST:event_launchLogsOnEditor

    /**
     * Launch browser with Logs file in order ton edit it
     * @param evt 
     */
    private void launchLogsOnBrowser(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchLogsOnBrowser

        
        File log = new File( LOGS_FILE_PATH );
        if(log.exists()) {
            appLauncher.executeBrowser(LOGS_FILE_PATH);
        } else {
            System.out.println("Logs file was not found.");
        }
    }//GEN-LAST:event_launchLogsOnBrowser

    /**
     * Launch editor with XML file in order ton edit it
     * @param evt 
     */
    private void launchLocationOnEditor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchLocationOnEditor

        File log = new File( ModelManager.getXMLFileName() );
        if(log.exists()) {
            appLauncher.executeEditor(ModelManager.getXMLFileName());
        } else {
            System.out.println("Config file was not found.");
        }
    }//GEN-LAST:event_launchLocationOnEditor

    /**
     * The STOP method
     * @param evt 
     */
    private void controlStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlStopActionPerformed
        sysTray.setIcon( SystemTray.STATUS.STOPPED  );
        infoStatusVar.setText("Stopped");
    }//GEN-LAST:event_controlStopActionPerformed

    private void goToProactiveWebSite(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToProactiveWebSite
        appLauncher.executeBrowser("http://proactive.inria.fr/");
    }//GEN-LAST:event_goToProactiveWebSite

    private void openLogFolder(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openLogFolder
        
    }//GEN-LAST:event_openLogFolder

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new mainWindows().setVisible(true);
            }
        });
    }
    
    private GUIEditorWindows GUIEditWindows = new GUIEditorWindows(this,true);
    private FileLocator fileLocator = new FileLocator();
    private ApplicationLauncher appLauncher = new ApplicationLauncher();
    private String LOGS_FILE_PATH = "ProActiveAgent-log.txt";
    private final String ICONS_MAIN_FRAME = "Images\\icon.ico";
    private final String TITLE_MAIN_FRAME = "ProActive Agent Control";
    private SystemTray sysTray = new SystemTray();
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelConfig;
    private javax.swing.JPanel PanelControl;
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JPanel PanelLogs;
    private javax.swing.JPanel PanelTitle;
    private javax.swing.JButton configBrowse;
    private javax.swing.JButton configGUIEdit;
    private javax.swing.JLabel configLocationText;
    private javax.swing.JTextField configLocationVar;
    private javax.swing.JButton configTextEdit;
    private javax.swing.JButton controlStart;
    private javax.swing.JButton controlStop;
    private javax.swing.JLabel infoNbRun;
    private javax.swing.JLabel infoNbRunVar;
    private javax.swing.JLabel infoStatus;
    private javax.swing.JLabel infoStatusVar;
    private javax.swing.JButton logsExplorer;
    private javax.swing.JButton logsNotepad;
    private javax.swing.JLabel logsView;
    private javax.swing.JLabel titlePicture;
    private javax.swing.JLabel titleText1;
    private javax.swing.JLabel titleText2;
    private javax.swing.JLabel titleText3;
    private javax.swing.JLabel titleURL1;
    private javax.swing.JLabel titleURL2;
    // End of variables declaration//GEN-END:variables
}
